### ISSUE TITLE
好像不支持php 7.4

### ISSUE THREAD

**Issue by Seevil** [upfor/juggler#7]
Deprecated : Array and string offset access syntax with curly braces is deprecated in D:\wwwroot\host\vendor\upfor\juggler\src\Juggler.php on line 817

环境
php7.4.3
mysql 8.0

**Comment by shockerli** [comment]
是的，从PHP 7.4开始不再支持大括号`{}`访问数组和字符串。已修复成方括号`[]`，更新到`v1.0.5`版本即可。

参考官方文档：https://www.php.net/manual/zh/migration74.deprecated.php
